version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: precificapro-postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=your_super_secret_password_12345
      - POSTGRES_DB=precificapro_db
    volumes:
      - precificapro_data:/var/lib/postgresql/data
    
    # ===============================================================
    # == ADIÇÃO: Garante que o contêiner só seja "saudável"    ==
    # == quando o banco de dados estiver pronto para conexões. ==
    # ===============================================================
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user -d precificapro_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  precificapro_data: